services:
  auth_postgres:
    image: postgres:16.4-bookworm
    container_name: auth_postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    networks:
      - floral
    ports:
      - "5432:5432"

networks:
  floral:
    driver: bridge

volumes:
  auth_postgres_data:
